server-name: ragflow-knowledge-base

default-base-url: http://192.168.1.100:9388/api/v1
default-api-key: ragflow-00000000000000000000000000000000

timeout: 60
timeout-param-enabled: false

transport: sse
sse-port: 41106

list-bases-enabled: true
get-base-enabled: true

datasets:
  - enabled: false
    dataset-id: 00000000000000000000000000000000
    search-tool-name: search_xxx_knowledge
    #search-tool-description: "Search knowledge about XXX(中文说明)."
    #search-tool-result: simple
    search-tool-description: "Search knowledge about XXX(中文说明). Results in JSON format, knowledge in the 'content' property."
    search-tool-result: json

  - enabled: true
    id-param-enabled: true
    search-tool-name: search_knowledge
    search-tool-description: "Search knowledge from specified knowledge base('knowledge_base_id'). Results in JSON format, knowledge in the 'content' property."
    search-tool-result: json
